language: go
sudo: false
go:
  - 1.5
  - tip
install:
  - go get github.com/mattn/gom
  - gom install
script:
  - gom build
  - ./geco
before_deploy:
  - go get github.com/mitchellh/gox
  - gom exec gox -os="linux darwin" -arch="amd64" -output="dist/{{.Dir}}_{{.OS}}_{{.Arch}}/{{.Dir}}"
  - cd dist && zip geco_linux_amd64.zip  geco_linux_amd64/geco  && cd -
  - cd dist && zip geco_darwin_amd64.zip geco_darwin_amd64/geco && cd -
deploy:
  provider: releases
  api_key:
    secure: Ngbq0738SoLtQDxD0Oo8FselloWqlAN3X1vMciPC2/JL3QqcXAkCnMlG/pu7RaQrENILzt5AfeqdP28hng3V4QJ+vu3NAIWjv2cXomo2uYopkz0xdA61vmQIoK15euWaG31XXxIfehoGYZ9bFGfqcsNni6REuBoKCRtoZs9j/gM=
  file:
    - dist/geco_linux_amd64.zip
    - dist/geco_darwin_amd64.zip
  skip_cleanup: true
  on:
    repo: minimum2scp/geco
    tags: true
    branch: master
    condition: "${TRAVIS_GO_VERSION} = 1.5"
